TODOlist_DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TODOlist_app.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

TODOlist_app/urls.py
from django.urls import path
from . import views


app_name = 'TODOlist_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_list/', views.add_list, name='add_list'),
    path('del_list/', views.del_list, name='del_list'),
    path('edit_title/<int:title_id>/', views.edit_title, name='edit_title'),
]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [

    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

TODOlist_app/models.py
from django.db import models


# Create your models here.
class TodoTitle(models.Model):
    """Class of TODO_lists titles"""
    title = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)


class TodoList(models.Model):
    """Class of individual TODOs list"""
    todo_text = models.TextField()
    order_num = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    title = models.ForeignKey(TodoTitle, on_delete=models.CASCADE)

    class Meta:
        ordering = ('order_num',)

TODOlist_app/forms.py
from django import forms
from django.forms import Textarea

from .models import TodoList, TodoTitle


class InputForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['todo_text']
        labels = {'todo_text': ''}

        widgets = {
            "todo_text": Textarea(attrs={"rows": 1, "class": "form-control"}),
        }


class addListForm(forms.ModelForm):
    class Meta:
        model = TodoTitle
        fields = ['title']
        labels = {'title': ''}

        widgets = {
            "title": Textarea(attrs={"rows": 1, "class": "form-control"}),
        }


class delListForm(forms.Form):
    pass

class editTitleForm(forms.ModelForm):
    class Meta:
        model = TodoTitle
        fields = ['title']
        labels = {'title': ''}

        widgets = {
            "title": Textarea(attrs={"rows": 1, "class": "form-control"}),
        }

TODOlist_app/views.py
from django.shortcuts import render, redirect
from .forms import InputForm, addListForm, delListForm, editTitleForm
from .models import TodoList, TodoTitle
from .service import getMaxOrderNum


# Create your views here.
def index(request):
    overall_list = {}
    for title in TodoTitle.objects.all():
        overall_list[title] = list(title.todolist_set.all())

    form_input = InputForm()

    if request.method == 'POST':
        # Whats consists in request.POST
        print(request.POST)

        # Converting QueryDict to list and retrieve second element. It is str type.
        query_dict_to_list = list(request.POST)[1]

        # Extracting action type
        action = request.POST.get(query_dict_to_list)

        if '↑' in action or '↓' in action or '☓' in action:

            title_id = query_dict_to_list.split(",")[0]

            work_entry_num = int(query_dict_to_list.split(",")[1])

            print("title_id =", title_id, "entry =", work_entry_num, "action =", action)

            work_title = TodoTitle.objects.get(id=title_id)
            print("Work title object =", work_title)
            work_entry = work_title.todolist_set.get(order_num=work_entry_num)
            print("Work todo object =", work_entry)

            # Searching for minimum and maximum order_num in a working TODOs list
            N_min, N_max = getMaxOrderNum(TodoList, work_title)

            if action == '↑' and work_entry_num != N_min:
                entry_to_up = work_title.todolist_set.get(order_num=work_entry_num)
                entry_to_down = work_title.todolist_set.get(order_num=work_entry_num - 1)
                while not entry_to_down:
                    work_entry_num -= 1
                    entry_to_down = work_title.todolist_set.get(order_num=work_entry_num - 1)
                print(f'Founded order_num to downing: {entry_to_down.order_num}')
                entry_to_up.order_num, entry_to_down.order_num = entry_to_down.order_num, entry_to_up.order_num
                try:
                    entry_to_up.save()
                    entry_to_down.save()
                except:
                    print('Database writing error!')
                return redirect('TODOlist_app:index')

            # if action == '↓' and work_entry_num != work_title.todolist_set.all().count() - 1:
            if action == '↓' and work_entry_num != N_max:
                entry_to_down = work_title.todolist_set.get(order_num=work_entry_num)
                entry_to_up = work_title.todolist_set.get(order_num=work_entry_num + 1)
                while not entry_to_up:
                    work_entry_num += 1
                    entry_to_up = work_title.todolist_set.get(order_num=work_entry_num + 1)
                print(f'Founded order_num to downing: {entry_to_up.order_num}')
                entry_to_up.order_num, entry_to_down.order_num = entry_to_down.order_num, entry_to_up.order_num
                try:
                    entry_to_up.save()
                    entry_to_down.save()
                except:
                    print('Database writing error!')
                return redirect('TODOlist_app:index')

            if action == '☓':
                del_entry = work_title.todolist_set.get(order_num=work_entry_num)
                print("Deleting todo string: ", del_entry.todo_text)
                try:
                    del_entry.delete()
                except:
                    print('Database writing error!')
                return redirect('TODOlist_app:index')

        if 'todo_text' in query_dict_to_list:
            # Adding entry to TODO_list
            query_dict_to_list = list(request.POST)[2]
            title_name = query_dict_to_list.split(",")[1]

            # Getting id of title
            title_object = TodoTitle.objects.get(title=title_name)
            print(title_object.id)

            N_min, N_max = getMaxOrderNum(TodoList, title_object)

            form_input = InputForm(request.POST)
            if form_input.is_valid():
                new_entry = TodoList(
                    todo_text=form_input.cleaned_data['todo_text'],
                    order_num=N_max + 1,
                    title=title_object)
                new_entry.save()
            return redirect('TODOlist_app:index')

    context = {'overall_list': overall_list, 'form_input': form_input}
    return render(request, 'TODOlist_app/index.html', context)


def add_list(request):
    if request.method == 'GET':
        form_addListForm = addListForm()

    if request.method == 'POST':
        form_addListForm = addListForm(data=request.POST)

        try:
            form_addListForm.save()
        except:
            print('Database writing error!')
        return redirect('TODOlist_app:index')

    context = {'form_addListForm': form_addListForm}
    return render(request, 'TODOlist_app/add_list.html', context)


def del_list(request):
    if request.method == 'GET':
        form_delListForm = delListForm()

    if request.method == 'POST':
        form_delListForm = delListForm()
        title_name_to_del = request.POST.get('title')

        try:
            TodoTitle.objects.get(title=title_name_to_del).delete()
        except:
            print('Database writing error!')
        return redirect('TODOlist_app:index')

    context = {'form_delListForm': form_delListForm, 'titles': TodoTitle.objects.all()}
    return render(request, 'TODOlist_app/del_list.html', context)


def edit_title(request, title_id):
    old_title = TodoTitle.objects.get(id=title_id)

    if request.method == 'GET':
        form_editTitle = editTitleForm(instance=old_title)

    if request.method == 'POST':
        form_editTitle = editTitleForm(data=request.POST, instance=old_title)
        if form_editTitle.is_valid():

            try:
                # TodoTitle.objects.get(title=title_name_to_del).delete()
                form_editTitle.save()
            except:
                print('Database writing error!')
            return redirect('TODOlist_app:index')

    context = {'form_editTitle': form_editTitle, 'title_id': title_id}
    return render(request, 'TODOlist_app/edit_title.html', context)

TODOlist_app/templates/TODOlist_app/add_list.html
{% extends 'TODOlist_app/base.html' %}


{% block content %}


<div class="container">
    <div class="row d-flex">
        <div class="col-3">
            <div class="card border shadow p-3 mb-5 bg-white">
                <div class="card-body">
                    <h4 class="card-title">Input new TODO list title</h4>
                    <form action="{% url 'TODOlist_app:add_list' %}" method='POST'>
                        {% csrf_token %}
                        {{ form_addListForm.as_p }}
                        <button type="submit" name="btn_add_entry" class="btn btn-success btn-sm lead">
                            Add
                        </button>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

TODOlist_app/templates/TODOlist_app/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Basic TODO List web application</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    {% load socialaccount %}
    <link rel="stylesheet" href="{% static 'TODOlist_app/style.css' %}">
    <script src="https://kit.fontawesome.com/cbd4c74f94.js" crossorigin="anonymous"></script>
</head>
<body>


<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'TODOlist_app:index' %}" class="nav-link px-2 text-secondary">Home</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                <li><a href="#" class="nav-link px-2 text-white">About</a></li>
            </ul>


            <div class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <button type="button" onclick="window.location.href={% url 'TODOlist_app:add_list' %};"
                        class="btn btn-outline-light me-2 btn-success">Add TODO card
                </button>
                <button type="button" onclick="window.location.href={% url 'TODOlist_app:del_list' %};"
                        class="btn btn-outline-light me-2 btn-danger">Delete TODO card
                </button>
            </div>
            <div class="text-end">

                {% if user.is_authenticated %}
                    Welcome, You are logged in as <span class="text-success">{{ user.username }}</span>
                        <a class="btn btn-outline-light me-2" href="{% url 'users:logout' %}">Logout</a>

                {% else %}
                    <a class="btn btn-outline-light me-2" href="{% url 'users:login' %}">Login</a>
                    <a class="btn btn-warning" href="{% url 'users:register' %}">Sign-up</a>
                {% endif %}

            </div>
        </div>
    </div>
</header>
<div class="nav-divider"></div>


{% block content %}

{% endblock content %}


</body>
</html>

TODOlist_app/templates/TODOlist_app/del_list.html
{% extends 'TODOlist_app/base.html' %}


{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card border shadow p-3 mb-5 bg-white">
                <div class="card-body">
                    <h4 class="card-title">Select List to remove</h4>

                    <form action="{% url 'TODOlist_app:del_list' %}" method='POST'>
                        {% csrf_token %}
                        <div class="form-check">
                            {% for title in titles %}
                            <input class="form-check-input" type="radio" name="title" value="{{ title.title }}">
                            <label class="form-check-label" for="{{ title.title }}">{{ title.title }}</label><br>
                            {% endfor %}
                        </div>
                        <button type="submit" name="btn_del_entry" class="btn btn-success btn-sm lead">
                            Remove
                        </button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock content %}

TODOlist_app/templates/TODOlist_app/edit_title.html
{% extends 'TODOlist_app/base.html' %}


{% block content %}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card border shadow p-3 mb-5 bg-white">
                <div class="card-body">
                    <h4 class="card-title">New TODO list</h4>
                    <form action="{% url 'TODOlist_app:edit_title' title_id %}" method='POST'>
                        {% csrf_token %}
                        {{ form_editTitle.as_p }}
                        <button type="submit" name="btn_edit_title_submit" class="btn btn-success btn-sm">
                            Save
                        </button>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

TODOlist_app/templates/TODOlist_app/index.html
{% extends 'TODOlist_app/base.html' %}


{% block content %}


{% verbatim %}
<!--<p>{{ overall_list }}</p>-->

<!--{% for titles, todos in overall_list.items %}-->

<!--<p>{{ titles.title }}</p>-->

<!--{% for todo in todos %}-->
<!--<p>{{ todo.todo_text }}</p>-->
<!--{% endfor %}-->

<!--{% endfor %}-->
{% endverbatim %}


<div class="container">

    <div class="row justify-content-center">


        {% for titles, todos in overall_list.items %}
        <!--Individual TODO_item card-->
        <div class="col-8 col-md-6 col-lg-6 col-xl-5 col-xxl-4">
            <div class="card shadow p-0 mb-5 bg-white">
                <div class="card-body mb-0 p-0">
                    <div class="card-header">
                        <h5 class="card-title">
                            {{ titles.title }}
                            <a class="btn btn-outline-primary btn-sm list-inline-item" href="{% url 'TODOlist_app:edit_title' titles.id %}">Edit</a>
                        </h5>

                        <p class="card-subtitle mb-2 text-muted"><small>{{ titles.date_added }}</small></p>
                    </div>


                    {% if not todos %}
                    <p class="card-text mb-1 mx-3">Insert first TODO record!</p>
                    {% endif %}
                    {% for todo in todos %}
                    <ul class="list-group list-group-flush border-0">
                        <li class="list-group-item">
                            <p class="card-text mb-1 fs-5">{{todo.todo_text}}</p>
                            <p class="card-subtitle mb-1 text-muted"><small>{{ todo.date_added }}</small></p>

                            <form action="{% url 'TODOlist_app:index' %}" method='POST'>
                                {% csrf_token %}
                                <input type="submit" name="{{ titles.id }},{{todo.order_num}}" value='↑'
                                       class="btn btn-outline-primary btn-sm" ;>
                                <input type="submit" name="{{ titles.id }},{{todo.order_num}}" value='↓'
                                       class="btn btn-outline-primary btn-sm" ;>
                                <input type="submit" name="{{ titles.id }},{{todo.order_num}}" value='☓'
                                       class="btn btn-outline-danger btn-sm" ;>
                            </form>
                        </li>
                    </ul>
                    {% endfor %}

                    <!--Input new todo_item card-->
                    <div class="mx-3">
                        <form action="{% url 'TODOlist_app:index' %}" method='POST'>
                            {% csrf_token %}
                            {{ form_input.as_p }}
                            <button type="submit" name="btn_add_entry,{{titles.title}}"
                                    class="btn btn-success btn-sm">Add
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock content %}